return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    main = "nvim-treesitter.configs",
    opts = {
      ensure_installed = {
        "c_sharp",
        "php",
        "html",
        "javascript",
        "typescript",
        "tsx",
        "css",
        "scss",
        "python",
        "lua",
        "json",
        "yaml",
        "json5",
        "markdown",
        "markdown_inline",
        "terraform",
        "hcl",
        "go",
        "gomod",
        "gowork",
        "c",
        "cpp",
        "rust",
        "bash",
        "dockerfile",
        "toml",
        "sql",
        "regex",
        "vim",
      },
      highlight = { enable = true },
      indent = { enable = true },
    },
  },
}
